version: 2.1

jobs:
  lint:
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - run: yarn install --dev
      - run: yarn run lint

  typecheck:
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - run: yarn install --dev
      - run: yarn run typecheck

  test:
    docker:
      - image: cimg/node:22.12.0
    steps:
      - checkout
      - run: yarn install --dev
      - run: yarn run test:coverage

workflows:
  version: 2
  main:
    jobs:
      - lint
      - typecheck
      - test
